name: Portfolio
description: Final project for the Postgraduate in Data Engineer at the Data Science Academy

on:
    push:
        branches:
            [main, dev_matheus]
    pull_request:
        branches:
            [main, dev_matheus]

jobs:
  code-test:
    name: ğŸ Code Python Test
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    container: python:3.11-bullseye
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y build-essential

      - name: Run tests
        run: |
            echo "Running tests ğŸ‘€"
            sleep 5
            echo "Tests successfully completed ğŸ«¦"


  tf-test:
    name: âš™ï¸ Terraform Test
    runs-on: ubuntu-latest
    needs: code-test # ğŸ”¥ Critical dependency!
    if: github.ref != 'refs/heads/main'
    container:
      image: mattheusxs/tf-1.11-cloud-sdk-515
    steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Authenticate to GCP
          uses: google-github-actions/auth@v2
          with:
                credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
                project_id: ${{ secrets.GCP_PROJECT_ID }}

        - name: validate Terraform configuration
          run: |
                cd ./configs/terraform
                echo 'ğŸš§ Creating credentials file... ğŸš§'
                echo '${{ secrets.TERRAFORM_TFVARS }}' > terraform.tfvars

                echo 'ğŸš§ Initializing and applying Terraform... ğŸš§'
                terraform init
                terraform workspace select dev || terraform workspace new dev
                terraform validate
                terraform test

                echo "Whole Terraform configuration is valid âœ…"

        - name: Clean up (opcional)
          run: |
                rm -f ./configs/terraform/credentials.json  #remove sensitive data


  tf-deploy-prd:
    name: âš™ï¸ Terraform Deploy (PRD)
    runs-on: ubuntu-latest
    container:
      image: mattheusxs/tf-1.11-cloud-sdk-515
      options: --entrypoint=""
    if: github.event_name == 'workflow_dispatch'
    steps:
        - name: Authenticate to GCP
          uses: google-github-actions/auth@v2
          with:
            credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
            project_id: ${{ secrets.GCP_PROJECT_ID }}

        - name: Terraform Deploy
          run: |
                cd ./configs/terraform
                echo 'ğŸš§ Creating credentials file... ğŸš§'
                echo '${{ secrets.TERRAFORM_TFVARS }}' > terraform.tfvars

                echo 'ğŸš§ Initializing and applying Terraform... ğŸš§'
                terraform init
                terraform workspace select dev || terraform workspace new dev
                terraform apply -auto-approve


  tf-destroy-prd:
    name: ğŸ”¨Terraform Destroy (PRD)
    runs-on: ubuntu-latest
    container:
      image: mattheusxs/tf-1.11-cloud-sdk-515
      options: --entrypoint=""
    if: github.event_name == 'workflow_dispatch'
    steps:
        - name: Authenticate to GCP
          uses: google-github-actions/auth@v2
          with:
            credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
            project_id: ${{ secrets.GCP_PROJECT_ID }}

        - name: Terraform Destroy
          run: |
                cd ./configs/terraform
                echo 'ğŸš§ Creating credentials file... ğŸš§'
                echo '${{ secrets.TERRAFORM_TFVARS }}' > terraform.tfvars

                echo 'ğŸš§ Initializing and applying Terraform... ğŸš§'
                terraform init
                terraform workspace select dev || terraform workspace new dev
                terraform apply -auto-approve
